# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0fcca1647e75b45ad67526f60ed5550187b6b5aea2dc1f2c9ffbf1f08d49bd26365d5dd6034482bc70811ee3e85a371cab9de6d007c769ecb11f9b65a64ac66

test:
  secret_key_base: b92200f023c87e9e4c26fc2a4c87fdb289caa1f01c7327130822df60734834d87c018c547d69f1358b6f5dbfb81c331a3d536ab21ea0d6e9947c3e6ffc4a8d65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
